### ISSUE TITLE
Distinguish pureJS components from iOS components in react-native

### ISSUE THREAD

**Issue by NishanthShankar** [madebyform/react-parts#10]
Now that react-native android is in the picture, will it be possible to have a list of components that will work on both react-native iOS and react-native android.

**Comment by dmfrancisco** [comment]
Hey @NishanthShankar, we are indeed planning on adding something to the interface to allow users to distinguish between React Native components that are for Android, iOS or both.

Thanks for your feedback! :+1:

**Comment by dmfrancisco** [comment]
Hello again @NishanthShankar! Just wanted to let you know that, although you can't yet filter per native platform, there's now a tiny icon on the bottom of list items.

If the repo has Objective-C code, then the iOS icon is displayed. If there's Java code, the Android icon is shown. So if none of the icons are displayed, it's a pure JS component. If both, it's also cross platform.

Thank you again for your feedback! :+1:

![reactparts](https://cloud.githubusercontent.com/assets/212106/10124859/9618f1ec-6558-11e5-993e-dab8280ade6f.png)

**Comment by NishanthShankar** [comment]
Awesome. Thank you guys

**Comment by NishanthShankar** [comment]
Hi,
Thanks a lot for this feature. Has made life a lot easier. But I recently bumped into this issue where the tagging is slightly off.
Example in hand : https://github.com/jsierles/react-native-view-snapshot

It does not support android but is marked as for android
