### ISSUE TITLE
Add filters 

### ISSUE THREAD

**Issue by yeso126** [madebyform/react-parts#14]
It would be nice to have filtering options, on reactweb and react-native like most downloaded or new

**Comment by dmfrancisco** [comment]
Hello Yesid, thank you for taking the time to submit this suggestion. It's definitely something that we want to add in the near future :+1: Thanks!

**Comment by dmfrancisco** [comment]
Hello @yeso126, we are working on a new catalog that adds both sorting and filtering capabilities. We are beta testing now and it's available here: https://js.coach

Thank you again for your feedback :+1:
