### ISSUE TITLE
TextInputLayout for react-native works on both android and ios 

### ISSUE THREAD

**Issue by zbtang** [madebyform/react-parts#27]
Could you help add this to react.parts? Thanks!

https://github.com/zbtang/React-Native-TextInputLayout

![preview](https://raw.githubusercontent.com/zbtang/React-Native-TextInputLayout/master/art/demo.gif)

**Comment by dmfrancisco** [comment]
Thanks for opening the issue in JS.coach. The package is now available here:
https://js.coach/react-native/rn-textinputlayout
