### ISSUE TITLE
add react-native-simple-dialogs

### ISSUE THREAD

**Issue by douglasjunior** [madebyform/react-parts#35]
Cross-platform simple dialogs for React Native based on the Modal component.

github: https://github.com/douglasjunior/react-native-simple-dialogs
npm: https://www.npmjs.com/package/react-native-simple-dialogs

### Android
<img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/android-dialog.png' width='250' /> <img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/android-progress.png' width='250' />

### iOS
<img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/ios-dialog.png' width='250' /> <img src='https://raw.githubusercontent.com/douglasjunior/react-native-simple-dialogs/master/screenshots/ios-progress.png' width='250' />

**Comment by dmfrancisco** [comment]
Thanks for opening this issue 👍 We've moved to a new catalog, JS.coach. The package is now available there: https://js.coach/react-native/react-native-simple-dialogs
