### ISSUE TITLE
add react-native-keyboard-manager

### ISSUE THREAD

**Issue by douglasjunior** [madebyform/react-parts#36]
Library that allows to prevent issues of keyboard sliding up and cover on React-Native iOS projects.

Github: https://github.com/douglasjunior/react-native-keyboard-manager
Npm: https://www.npmjs.com/package/react-native-keyboard-manager

**Comment by dmfrancisco** [comment]
Thanks for opening this issue 👍 We've moved to a new catalog, JS.coach. The package is now available there: https://js.coach/react-native/react-native-keyboard-manager
