### ISSUE TITLE
How often do you refresh the list?

### ISSUE THREAD

**Issue by Kureev** [madebyform/react-parts#6]
Hi there,

I added `react-component` tag to [my library](https://github.com/Kureev/react-native-side-menu) more than one day ago but it's still not indexed. Is there something else what I missed?

**Comment by dmfrancisco** [comment]
Hi @Kureev, we're moving from manual submissions to automated data retrieval. At the same time, we are working on a new section for react components for web, and reviewing a lot of stuff manually.  Having said that, I just included your package :wink: It should be on the site now. Thanks for your contribution!

**Comment by Kureev** [comment]
Thanks for that! :wink:
