### ISSUE TITLE
Please add two new modules to repo

### ISSUE THREAD

**Issue by ghost** [madebyform/react-parts#8]
I would do a pull request in components.son but it looks like the instructions changed to not suggest doing this anymore?

Please add:

react-native-communications https://github.com/anarchicknight/react-native-communications

react-native-message-composer https://github.com/anarchicknight/react-native-message-composer

Both are also available on npm

**Comment by dmfrancisco** [comment]
Thank you for your contribution @anarchicknight! They should be there now :+1:

**Comment by ghost** [comment]
thanks
